<?php include 'con_db.php'?>

<!DOCTYPE html>
<html lang="en">
<head>
<title>Astrolearn</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8">

</head>
<body>

<?php include 'header.php'?>

<!-- Image Map Generated by http://www.image-map.net/ -->

<div class="swf">

 <div class="headings1">
 <h5> The Solar system </h5>
 <p class="p"> The solar system is made up the sun, stars and planets which are bound together though gravity. The solar system is a gravitationally bound system that contains objects which orbit the sun. the largest objects are the 8 planets, the rest are dwarf planets and small solar system bodies. Solar system has been around for 4.568 billion years old. The system was created when the gravitational collapse of a giant interstellar molecular cloud occurred 4.6 billion years ago. The planets starting nearest to the sun are Mercury, Venus, Earth, Mars, Jupiter, Saturn and Uranus. Pluto is known as a dwarf planet and is the final to complete the solar system.
 The majority of the mass from the system is in the Sun and the rest is contained in Jupiter.
 </p>
 </div>

 <video width="320" height="240" autoplay="autoplay" loop="loop">
   <source src="vid/solar_system.mp4" type="video/mp4">
   <source src="movie.ogg" type="video/ogg">
 </video>

</div>

</div>

      <div class="flex-container">

       <div class="p"> <p class="sun_headings">MERCURY</p> Closest to the sun. <b>Smallest</b> out of the eight planets. It takes <b>88 earth days</b> for mercury and three rotation on its axis for every two orbits. Due to where Mercury is placed in the solar system, it has a <b>surface temperature of 450 degrees Celsius</b>. NASA discovered in 2012 that there was water ice found in craters where the sun does not reach in its North Pole at any point during its orbit.<br>
        Although this is the smallest planet, it is still shrinking every day. The planet is made up of just one continental plate. When the core cools and solidifies, it reduces the volume of the planet which is the main reason for its shrinkage. <br>
        Mercury has a metallic core which is roughly <b>2,200 to 2,400 miles</b> wide which makes it the second densest planet, earth being the first.<br>
        The average distance from the sun is around 35,983,095 miles away.

        </div>

      <div> <p class="sun_headings">VENUS</p> Venus is the second brightest natural object that is in space. Can sometimes be referred to as the morning and evening star. It is the <b>third largest</b> object in the sky after the Moon and Sun. It is also known as being referred to as Earth’s sister planet due to it having a similar mass and size. <br> <b>Venus is the closest planet to Earth</b> and its surface is hidden by clouds which are formed by sulphuric acid. A day on Venus is longer that one year to Earth. <br> It is once said that a billion years ago, the climate on Venus was very similar to Earth’s. It is also the hottest planet in the solar system, with an average surface temperature of 462 degrees Celsius. <br> The atmosphere on Venus is 92 times stronger than Earth. Venus is one of the only planets which rotates clockwise unlike the rest which anti-clockwise. The age of Venus is estimated to <b>300-400 million years old.</b> The surface on Earth is about 100 million years old.
      </div>

      <div> <p class="sun_headings">EARTH</p> Orbits the sun once every <b>365.25 days</b>. Due to our calendar years have 365 days in them, we have a leap year every four years which makes up for the difference. Earth is <b>93 million miles away from the Sun.</b> Earth has many layers. The inner core which is made from iron and nickel that is around 759 miles wide and is as hot as <b>9,800 degrees Fahrenheit.</b> This is then surrounded by an outer core which is 1,800 miles thick layer of molten rock. 70% of the surface is covered by liquid such as oceans. Tectonic plates move very slowly and when the collide it results in natural disasters such as earthquakes and tsunamis.The atmosphere is made up of 78% Nitrogen, 21% Oxygen and one percent other gases. For example, carbon Dioxide, Water Vapour and argon. Earth’s surface temperature is around 57 degrees, without our atmosphere, it would be 0 degrees. Due to humans adding to greenhouse gases, the atmosphere had risen by <b> 1.8 degrees Fahrenheit. </b>
        </div>
      </div>

      <div class="flex-container">
        <div> <p class="sun_headings">MARS </p> Mars is around 142 Million miles away from the Sun. It is the <b>4th planet from the Sun.</b> <br> It orbits the sun at an average speed of 14.5 miles per second.
        Its diameter is around 4,220 miles and its tilt of axis is <b>25 degrees.</b>
        The average temperature is around <b> -81 degrees Fahrenheit.</b>
        The atmosphere is made up of mostly carbon dioxide and water vapor.
        Mars has 2 moons orbiting it. A year on Mars is a lot longer that Earth. It is 687 days compared to our 365 days. The core of earth and mars is quiet similar, yet the structure is still unknown. <br> The gravity on Mars is <b>62.5% less than Earth.</b> Meaning your steps would have a little extra bounce to them.

        </div>

        <div> <p class="sun_headings">JUPITER</p> Out of all the planets, Jupiter is known to be the grandest. The size of Jupiter is much larger than Earth. It is the <b>fifth planet from the Sun.</b> it is 484 miles away from the sun. Jupiter rotates only once every 10 hours. It takes 12 earth years for Jupiter to orbit the sun once. Jupiter is made up of gas and lacks an Earth- like surface. It is made up of mostly hydrogen and helium <b>Jupiter has 75 moons.</b> As we know it now, life cannot be supported on Jupiter; however, there has been oceans beneath their crusts found on some of its moons. There have been nine spacecrafts that have visited Jupiter over the years. Seven only flew by and 2 have orbited it.
        </div>

          <div> <p class="sun_headings">SATURN</p> Saturn is the <b>6th planet from the Sun</b>, and it orbits it from a distance of 886 million miles away from the sun. The diameter of Saturn would be 9 Earth’s side by side. Not including the rings.It takes 10.7 hours for Saturn to rotate once on its axis. It takes 29 Earth years for it to orbit the sun. It doesn’t have a solid surface and is a gas giant planet. The air is mostly hydrogen and helium. <b>It has 53 moons</b> which are known and has an <b>additional 29 moons</b> which are awaiting confirmation. Meaning it has 82 moons in total. It has seven rings and several gaps divisions between them. There have been missions to Saturn.
          Saturn cannot support life either, however some of the moons have conditions that could suggest otherwise. It is said that two tons of Saturn’s mass came from Earth.

        </div>
      </div>

      <div class="flex-container">
        <div> <p class="sun_headings">URANOS</p> Uranus is around 4 times wider than Earth, it orbits the Sun from <b>1.8 billion miles away.</b>
        Uranus takes 17 hours to rotate once on its axis and takes about 84 earth days to orbit the sun once. Uranus is also known as the ice giant; the mass is hot however it has dense icy materials. Some of these are water, methane and ammonia. Its atmosphere is mostly molecular hydrogen and atomic helium and has a small amount of methane. There are also many moons orbiting this planet, 27 known and that are named from the work of William Shakespeare and Alexander Pope. There are <b>13 known rings</b> around Uranus. The inner rings are narrow and darker in colour whereas the outer ones are bright.
        There has only been one spaceship to pass by Uranus which was Voyager 2, but none have orbited it. <b>Uranus is also unable to support life according to scientists.</b> Like Venus, Uranus rotes clockwise and is unique due to it rotating on its side.

        </div>

        <div> <p class="sun_headings">NEPTUNE</p> Neptune is around 4.5 billion kilometers away from the Sun. It is dark and cold due it being <b>eight planet </b> away from the Sun. It has supersonic winds and is a giant ice planet due to where it is located within the Solar System. Most of the planet’s mass is hot and dense fluid, water, methane and ammonia is what makes it ‘icy’. The atmosphere is mainly molecular hydrogen, methane and atomic helium. It has <b>14 moons</b> and has a minimum of 5 main rings around it and four ring arcs. Neptune is unable to support life, it is the only planet this is not visible to the naked eye; a telescope is needed to be able to see as far as Neptune. The planet is around four times bigger than Earth. It takes 16 hours for it to rotate once and around 165 Earth years to orbit the Sun just once! (this is a Neptunian year). Only one space craft has ever been to Neptune which was the NASA voyager 2 in 1989.
        </div>

          <div> <p class="sun_headings">PLUTO</p> Pluto is much smaller than Earth’s moon. It has a heart shaped glacier that is around the same size of Texas. It has beautiful and fascinating blue skies, spinning moons and mountains which are around the same height of the Rockies in Canada! It even snows, but not the same as you may think. The snow is red!
          Pluto orbits the sun around <b>3.6 billion kilometres away</b>.  One year on Pluto is about <b>248 Earth years</b>. Compared to our 24 hours on Earth, Pluto’s days last 153 hours which is the same as 6 Earth days.
          It is classified as a dwarf planet and has a very thin atmosphere made up of Nitrogen, methane and carbon monoxide. It has a blue tint to the atmosphere and has a very distinctive haze. It has 5 moons and no rings around it. The surface of Pluto is very cold, around -378 to -396 degrees Fahrenheit.
        </div>
      </div>
</div>

<br>

<?php include 'solarquiz.php'?>



</body>
</html>
